# Generated by Django 5.0.8 on 2024-08-23 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='user_bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
